displayName=Real Trade Values
author=theokgatsby
description=Shows actual trade values when exceeding the 2.1B integer limit and allows custom 3rd age item values.
tags=trade,value,prices,lots,3rd age,third age,cash,over max cash
version=
plugins=com.realtradevalues.RealTradeValuesPlugin
build=standard